### PR TITLE
Update specs where missing and outdated tests were found

### PR DESCRIPTION
**Pull request by Kizr**
## Context

As part of learning more about our codebase I opted to go through the application file by file and compare them to their corresponding `*_spec.rb` files. Increasing our code coverage where there were missed or outdated tests seemed like an easy value add whilst I was onboarding.

## Changes proposed in this pull request

- Updated some tests to add missed methods and associations
- Added new spec files where none were present

## Guidance to review

Run the test suite and make sure all tests are passing and that I have not made any stylistic decisions that go against the app's code style.

## Link to Trello card

[Investigate and improve test coverage](https://trello.com/c/psXhmCl9)

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated or [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by ollietreend — APPROVED** [review]
Lovely work – thanks for doing this @Kizr! ✨🧹

BTW: Looks like you have a merge conflict so you will want to rebase against `main`.

**Review by Nitemaeric — APPROVED** [review]
https://github.com/DFE-Digital/itt-mentor-services/pull/336/commits/9e9b03efe865476faf239a1b3acc6de1fe847e3f addresses quite a few issues all in a single commit. It would be great if this commit could be split out into the individual issues it addresses.

As for the code itself, 🚀. Awesome stuff!

**Comment by Kizr** [comment]
> [9e9b03e](https://github.com/DFE-Digital/itt-mentor-services/commit/9e9b03efe865476faf239a1b3acc6de1fe847e3f) addresses quite a few issues all in a single commit. It would be great if this commit could be split out into the individual issues it addresses.
> 
> As for the code itself, 🚀. Awesome stuff!

I 100% agree with you, this was sloppy on my part. As it stands the branch is protected so I cannot force push a revised history, I could open a new branch with the history if you think it's prudent to do so?

**Comment by ollietreend** [comment]
There's some weirdness going on here because @Kizr still hasn't been added to the [DFE-Digital](https://github.com/dfe-digital) org. So to avoid complication, I'm going to merge this PR as is because it's still an improvement despite that commit not being split out.

**Pull request closed without merging**
