### PR TITLE
Initial draft for testing practices ADR

### PR DESCRIPTION
**Pull request by Nitemaeric**
## Context

We want to align on our testing practices to make testing both easier to write and to review.

## Changes proposed in this pull request

- Add ADR related to Testing Practices

## Guidance to review

- There's a lot of other testing practices we may want to agree on. Feel free to suggest additions.
- Click [here](https://github.com/DFE-Digital/itt-mentor-services/blob/adr/testing-practices/adr/00003-testing-practices.md) to preview the ADR.

## Link to Trello card

https://trello.com/c/jzu6Vgel/69-write-up-adr-for-testing-practices

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated or [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by ollietreend** [comment]
Does this ADR proposal mean the 'Sign In as Persona' feature test will need to be converted to a system test?

https://github.com/DFE-Digital/itt-mentor-services/blob/6c36835135bf613faee30025b3c44799973f045d/spec/features/personas/sign_in_as_persona_spec.rb

**Comment by Nitemaeric** [comment]
> Does this ADR proposal mean the 'Sign In as Persona' feature test will need to be converted to a system test?
> 
> https://github.com/DFE-Digital/itt-mentor-services/blob/6c36835135bf613faee30025b3c44799973f045d/spec/features/personas/sign_in_as_persona_spec.rb

Yes. We would want to. There's this article I've run into that addresses these migrations: https://railsnotes.xyz/blog/feature-specs-to-system-specs

**Comment by CatalinVoineag** [comment]
> > Does this ADR proposal mean the 'Sign In as Persona' feature test will need to be converted to a system test?
> > https://github.com/DFE-Digital/itt-mentor-services/blob/6c36835135bf613faee30025b3c44799973f045d/spec/features/personas/sign_in_as_persona_spec.rb
> 
> Yes. We would want to. There's this article I've run into that addresses these migrations: https://railsnotes.xyz/blog/feature-specs-to-system-specs

In that article, it also suggests to move to rack for running the system specs when you don't have javascript and use selenium when you have.

This might speed up our specs a bit considering we are quite light on javascript

**Review by CatalinVoineag — APPROVED** [review]

**Review by ollietreend — APPROVED** [review]
Looks good to me. Let's update the "Status" of this ADR to "Accepted" before merging. 👍🏻 

We'll need to create Trello cards to rewrite those existing tests which don't fit this new approach.

**Pull request merged**
